version: '3.8'

services:
  di-auth-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    environment:
      - ENVIRONMENT="development"
      - API_BASE_URL=""
    restart: on-failure
    networks:
      - di-net

networks:
  di-net: