version: '3.8'

services:
  di-auth-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9230:9230
    volumes:
      - ./:/app
    environment:
      - ENVIRONMENT="development"
      - API_BASE_URL=
      - SESSION_EXPIRY=3600000
      - SESSION_SECRET="secret"
      - API_KEY=
      - FRONTEND_API_BASE_URL=
      - ANALYTICS_COOKIE_DOMAIN=localhost
    restart: on-failure
    networks:
      - di-net

  redis:
    image: redis:6.0.5-alpine
    ports:
      - 6379:6379
    networks:
      - di-net

  di-auth-stub:
    build:
      context: .
      dockerfile: Dockerfile-stub
    links:
      - di-auth-frontend
    ports:
      - 2000:2000
    environment:
      - ENVIRONMENT="development"
      - API_BASE_URL=
      - FRONTEND_API_BASE_URL=
      - TEST_CLIENT_ID=
    restart: on-failure
    networks:
      - di-net

networks:
  di-net: